# --- Directories ---
SRC_DIR   := src
BUILD_DIR := build
BIN_DIR   := bin

# --- Toolchain ---
CC := i686-elf-gcc
LD := i686-elf-ld

# --- Flags ---
INCLUDES := -I$(SRC_DIR)
CFLAGS   := -g -ffreestanding -falign-jumps -falign-functions -falign-labels \
            -falign-loops -fstrength-reduce -fomit-frame-pointer -finline-functions \
            -Wno-unused-function -fno-builtin -Werror -Wno-unused-label -Wno-cpp \
            -Wno-unused-parameter -nostdlib -nostartfiles -nodefaultlibs \
            -Wall -O0 -std=gnu99 -MMD -MP
ASFLAGS  := -f elf -g

# --- Auto-discovery ---
# All .c files under src/
C_SOURCES   := $(shell find $(SRC_DIR) -name '*.c')
# All .asm files under src/, EXCEPT boot.asm (which is special)
ASM_SOURCES := $(shell find $(SRC_DIR) -name '*.asm' -not -path '$(SRC_DIR)/boot/*')

# Convert src/foo/bar.c   -> build/foo/bar.o
# Convert src/foo/bar.asm -> build/foo/bar.asm.o
C_OBJECTS   := $(patsubst $(SRC_DIR)/%.c,   $(BUILD_DIR)/%.o,     $(C_SOURCES))
ASM_OBJECTS := $(patsubst $(SRC_DIR)/%.asm, $(BUILD_DIR)/%.asm.o, $(ASM_SOURCES))

# kernel.asm.o must be linked FIRST so the entry point is at the start of .text.
# Pull it out, then put everything else after it.
KERNEL_ENTRY := $(BUILD_DIR)/kernel.asm.o
OTHER_OBJECTS := $(filter-out $(KERNEL_ENTRY), $(C_OBJECTS) $(ASM_OBJECTS))
LINK_OBJECTS  := $(KERNEL_ENTRY) $(OTHER_OBJECTS)

# Header dependency files (auto-generated by -MMD)
DEPS := $(C_OBJECTS:.o=.d)

# --- Targets ---
.PHONY: all clean

all: $(BIN_DIR)/os.bin

$(BIN_DIR)/os.bin: $(BIN_DIR)/boot.bin $(BIN_DIR)/kernel.bin
	rm -f $@
	dd if=$(BIN_DIR)/boot.bin >> $@
	dd if=$(BIN_DIR)/kernel.bin >> $@
	dd if=/dev/zero bs=512 count=100 >> $@

$(BIN_DIR)/kernel.bin: $(LINK_OBJECTS) | $(BIN_DIR)
	$(LD) -g -relocatable $(LINK_OBJECTS) -o $(BUILD_DIR)/kernelfull.o
	$(CC) $(CFLAGS) -T $(SRC_DIR)/linker.ld -o $@ $(BUILD_DIR)/kernelfull.o

$(BIN_DIR)/boot.bin: $(SRC_DIR)/boot/boot.asm | $(BIN_DIR)
	nasm -f bin $< -o $@

# Pattern rule: build/foo/bar.o  from  src/foo/bar.c
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(INCLUDES) $(CFLAGS) -c $< -o $@

# Pattern rule: build/foo/bar.asm.o  from  src/foo/bar.asm
$(BUILD_DIR)/%.asm.o: $(SRC_DIR)/%.asm
	@mkdir -p $(dir $@)
	nasm $(ASFLAGS) $< -o $@

$(BIN_DIR):
	@mkdir -p $@

clean:
	rm -rf $(BUILD_DIR) $(BIN_DIR)

# Include auto-generated header dependencies
-include $(DEPS)
